---
- hosts: database
  become: true
  tasks:
  - name: Install apt repository
    apt_repository:
      repo: deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main
      state: present
    register: repoadd
  - name: Add apt key
    apt_key:
      url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
      state: present
  - name: update apt cache
    apt:
      update_cache: yes
    when: repoadd.changed
  - name: Install list of dependency packages for Postgres
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - libpq-dev
      - python-psycopg2
      - postgresql-9.5
  - lineinfile:
      dest: /etc/postgresql/9.5/main/postgresql.conf
      regexp: '^listen_addresses'
      insertafter: '^#listen_addresses'
      line: "listen_addresses = '*'"
    notify: restart postgres
  - lineinfile:
      dest: /etc/postgresql/9.5/main/pg_hba.conf
      line: "host  all  all   all   md5"
    notify: restart postgres
  handlers: 
   - name: restart postgres
     service:
      name: postgresql
      state: reloaded

- hosts: database
  become: true
  become_user: postgres
  
  vars:
    dbname: f8forum_db
    dbuser: f8forum_user
    dbpassword: mysupersecretpassword

  tasks:
  - name: ensure database is created
    postgresql_db: 
      name: "{{ dbname }}"
  - name: ensure user has access to database
    postgresql_user: 
      db: "{{ dbname }}" 
      name: "{{ dbuser }}" 
      password: "{{ dbpassword }}" 
      priv: ALL
      role_attr_flags: NOSUPERUSER,NOCREATEDB
  - name: ensure no other user can access the database
    postgresql_privs: 
      db: "{{ dbname }}" 
      role: PUBLIC 
      type: database 
      priv: ALL 
      state: absent
